"""
Django settings for njogush project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-honx4+d)af-uknv&&pw9q*zki%(sp)svo2jls3iqnnyxe1il4r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ! TO BE DONE - add hosts dynamically
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]


# Application definition

INSTALLED_APPS = [
    ## Added Apps 
    'daphne',
    'rest_framework',
    'rest_framework.authtoken', # TODO https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication,
    'corsheaders', # TODO https://pypi.org/project/django-cors-headers/

    'user',
    'chat',
    'build_tool',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # TODO https://pypi.org/project/django-cors-headers/
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'njogush.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'njogush.context_processor.add_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'njogush.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 🏁 START OF NON-BOILERPLATE SETTINGS 🏁
from decouple import config
from decouple import Csv

DEBUG = config('DEBUG', default=False, cast=bool)

# os.environ['ALLOWED_HOSTS'] = '.localhost, .herokuapp.com'
# ALLOWED_HOSTS += config('ALLOWED_HOSTS', default='127.0.0.1', cast=Csv())
allowed_hosts_default = "127.0.0.1, localhost"
ALLOWED_HOSTS += config('ALLOWED_HOSTS', default=allowed_hosts_default, cast=Csv())

TIME_ZONE = 'Africa/Nairobi' # UTC

# TODO https://docs.djangoproject.com/en/4.0/topics/auth/default/#the-login-required-decorator
LOGIN_URL = "user:login"

LOGIN_REDIRECT_URL = "build_tool:index"

import glob

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL ='/media/'

# TODO https://pypi.org/project/django-cors-headers/
CORS_ALLOWED_ORIGINS = [
#     "https://example.com",
#     "https://sub.example.com",
#     "http://localhost:8080",
#     "http://127.0.0.1:9000",
    # <<<<<<<<>>>>>>>
    # npm run vite
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    # <<<<<<<<>>>>>>>
    "http://127.0.0.1:6564",
    "http://localhost:6564",
]

# TODO https://channels.readthedocs.io/en/stable/tutorial/part_1.html#integrate-the-channels-library
ASGI_APPLICATION = "njogush.asgi.application"

# TODO https://stackoverflow.com/questions/60010487/python-glob-path-issue
# ./[build_tool]/templates/[build_tool_vue]/dist
static_path = [os.path.normpath(i) for i in glob.glob("./*/templates/*/dist/static")]
# print(static_path)
STATICFILES_DIRS = static_path

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

CSRF_TRUSTED_ORIGINS = [
    # 'https://example.com',
]
csrf_trusted_origins_default = ""

# + https://docs.djangoproject.com/en/4.0/topics/email/#module-django.core.mail
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)

DEFAULT_FROM_EMAIL=EMAIL_HOST_USER # + https://docs.djangoproject.com/en/4.0/topics/auth/default/#django.contrib.auth.views.PasswordResetView.from_email

ADMINS = [
    # ('John', 'john@example.com'),
    # ('Mary', 'mary@example.com')
]
ADMINS.append(config('ADMINS', default='', cast=Csv(post_process=tuple)))

EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX', default='[Ohala] ')

# TODO DJANGO REST FRAMEWORK
# + https://www.django-rest-framework.org/tutorial/5-relationships-and-hyperlinked-apis/#adding-pagination
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # + https://www.django-rest-framework.org/api-guide/authentication/#setting-the-authentication-scheme
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # + https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication
        'rest_framework.authentication.TokenAuthentication', # ! IMPORTANT => https://www.django-rest-framework.org/api-guide/authentication/#apache-mod_wsgi-specific-configuration
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        'rest_framework.permissions.IsAuthenticated',
    ]
}

CUSTOM_SYSTEM_NAME = 'Njogush'
REMOTE_MODE = config('REMOTE_MODE', default=False, cast=bool) # ! IMPORTANT
