# Generated by Django 4.2.8 on 2023-12-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build_tool', '0004_rename_file_step_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='build_tool.project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_sessions', to='build_tool.project')),
            ],
        ),
    ]
