# Generated by Django 4.2.8 on 2024-01-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_tool', '0006_alter_buildsession_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsession',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
