# Generated by Django 4.2.8 on 2024-01-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_tool', '0008_step_is_parallel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='is_parallel',
        ),
    ]
