# Generated by Django 4.2.8 on 2024-01-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_tool', '0009_remove_step_is_parallel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
