# Generated by Django 4.2.8 on 2024-01-13 10:52

from django.db import migrations

def fill_nulls(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Project = apps.get_model("build_tool", "Project")
    
    count = 0
    for project in Project.objects.filter(identifier__isnull=True):
        count += 1
        project.identifier = f"{count}"
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('build_tool', '0010_project_identifier'),
    ]

    operations = [
        migrations.RunPython(fill_nulls),
    ]
