# Generated by Django 4.2.8 on 2024-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_tool', '0012_alter_project_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
