# Generated by Django 4.2.8 on 2025-01-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_tool', '0014_buildsession_command_arguements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildsession',
            old_name='command_arguements',
            new_name='command_arguments',
        ),
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
