# Generated by Django 4.2.8 on 2025-01-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_tool', '0015_rename_command_arguements_buildsession_command_arguments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='use_command_arguements',
            field=models.BooleanField(default=True),
        ),
    ]
